name: Ops Bot – Apply Patch from Issue Comment

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  apply-patch:
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.comment.body, '/apply-patch') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract patch from comment
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const body = (context.payload.comment && context.payload.comment.body) || '';
            const match = body.match(/```(patch|diff)\n([\s\S]*?)```/i);
            if (!match) {
              core.setFailed('Не найден код-блок ```patch``` или ```diff``` в комментарии.');
              return;
            }
            const patch = match[2];
            const fs = require('fs');
            fs.writeFileSync('incoming.patch', patch, 'utf8');
            core.setOutput('has_patch', 'true');

      - name: Show patch (debug)
        if: steps.extract.outputs.has_patch == 'true'
        run: |
          echo "------ PATCH START ------"
          sed -n '1,200p' incoming.patch
          echo "------ PATCH END --------"

      - name: Configure git author
        run: |
          git config user.name  "ops-bot"
          git config user.email "ops-bot@users.noreply.github.com"

      - name: Create work branch
        run: |
          BRANCH="ops/patch-${{ github.run_id }}"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          git checkout -b "$BRANCH"

      - name: Apply patch
        id: apply
        run: |
          set -e
          git apply --whitespace=fix --reject incoming.patch || {
            echo "::error::Патч применился с конфликтами. Загружаю .rej файлы как артефакты."
            exit 2
          }

      - name: Commit & push
        run: |
          git add -A
          git commit -m "Apply patch via Ops Bot (#${{ github.event.issue.number || 'manual' }})"
          git push -u origin "$BRANCH"

      - name: Open Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const branch = process.env.BRANCH;
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: branch,
              base: 'main',
              title: 'Ops Bot: apply patch',
              body: 'Автогенерация PR из комментария с патчем.'
            });
            core.info(`PR: ${pr.html_url}`);

      - name: Comment back (success)
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const body = "✅ Патч применён, создан PR. Проверьте вкладку Pull requests.";
            if (context.payload.comment) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                body
              });
            }

      - name: Upload rejects (if conflicts)
        if: failure() && steps.apply.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: patch-rejects
          path: |
            **/*.rej
            **/*.orig
            incoming.patch
